# Generated by Django 2.2.6 on 2019-11-14 13:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200)),
                ('location', models.CharField(choices=[('K', 'KAGERA'), ('M', 'MWANZA')], default='none', max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('nationality', models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200)),
                ('highest_qualification', models.CharField(choices=[('DE', 'Deploma'), ('BA', 'Bachelor')], max_length=200)),
                ('years_of_exprience', models.CharField(choices=[(3, '3year'), (1, 'No exprience'), (2, '1year'), (4, '3year')], max_length=200)),
                ('cv', models.FileField(blank=True, upload_to='cv/')),
                ('receive_op_jobs', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Jobseekers list',
            },
        ),
    ]
