# Generated by Django 2.2.6 on 2019-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='location',
            field=models.CharField(choices=[('M', 'MWANZA'), ('K', 'KAGERA')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[(1, 'No exprience'), (3, '3year'), (4, '3year'), (2, '1year')], max_length=200),
        ),
    ]
