# Generated by Django 2.2.6 on 2019-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_auto_20191114_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='location',
            field=models.CharField(choices=[('K', 'KAGERA'), ('M', 'MWANZA')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='nationality',
            field=models.CharField(choices=[('AL', 'Algeria'), ('AN', 'Angola')], max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[('four', '3year'), ('no', 'No exprience'), ('one', '1year'), ('three', '3year')], max_length=200),
        ),
    ]
