# Generated by Django 2.2.6 on 2019-11-18 10:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0003_auto_20191114_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='location',
            field=models.CharField(choices=[('K', 'KAGERA'), ('M', 'MWANZA')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='nationality',
            field=models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[('three', '3year'), ('no', 'No exprience'), ('one', '1year'), ('four', '3year')], max_length=200),
        ),
    ]
