# Generated by Django 2.2.6 on 2019-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0004_auto_20191118_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='highest_qualification',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('DE', 'Deploma')], max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[('no', 'No exprience'), ('one', '1year'), ('four', '3year'), ('three', '3year')], max_length=200),
        ),
    ]
