# Generated by Django 2.2.6 on 2019-11-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0006_auto_20191118_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekersmodel',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='jobseekersmodel',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='highest_qualification',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('DE', 'Deploma')], max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='location',
            field=models.CharField(choices=[('M', 'MWANZA'), ('K', 'KAGERA')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='nationality',
            field=models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[('no', 'No exprience'), ('one', '1year'), ('four', '3year'), ('three', '3year')], max_length=200),
        ),
    ]
