# Generated by Django 2.2.6 on 2019-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0008_auto_20191118_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='highest_qualification',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('DE', 'Deploma')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='nationality',
            field=models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='receive_op_jobs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersmodel',
            name='years_of_exprience',
            field=models.CharField(choices=[('four', '3year'), ('one', '1year'), ('no', 'No exprience'), ('three', '3year')], max_length=200, null=True),
        ),
    ]
