# Generated by Django 2.2.6 on 2019-11-18 12:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0009_auto_20191118_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekersPersonalIfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('M', 'MWANZA'), ('K', 'KAGERA')], default='none', max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('nationality', models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jobseekers list',
            },
        ),
        migrations.DeleteModel(
            name='JobseekersModel',
        ),
    ]
