# Generated by Django 2.2.6 on 2019-11-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0010_auto_20191118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='location',
            field=models.CharField(choices=[('K', 'KAGERA'), ('M', 'MWANZA')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='nationality',
            field=models.CharField(choices=[('AL', 'Algeria'), ('AN', 'Angola')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='JobseekersJobinfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(choices=[('BA', 'Bachelor'), ('DE', 'Deploma')], max_length=200, null=True)),
                ('years_of_exprience', models.CharField(choices=[('no', 'No exprience'), ('one', '1year'), ('three', '3year'), ('four', '3year')], max_length=200, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('receive_op_jobs', models.IntegerField(default=0, null=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekers.JobseekersPersonalIfor')),
            ],
            options={
                'verbose_name_plural': 'Jobseekers list',
            },
        ),
    ]
