# Generated by Django 2.2.6 on 2019-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0011_auto_20191118_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekersjobinfor',
            options={'verbose_name_plural': 'Jobseekers job infor'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerspersonalifor',
            options={'verbose_name_plural': 'Jobseekers personali nfo'},
        ),
        migrations.RemoveField(
            model_name='jobseekersjobinfor',
            name='receive_op_jobs',
        ),
        migrations.AddField(
            model_name='jobseekersjobinfor',
            name='receive_job_notifation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='highest_qualification',
            field=models.CharField(choices=[('DE', 'Deploma'), ('BA', 'Bachelor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='years_of_exprience',
            field=models.CharField(choices=[('one', '1year'), ('four', '3year'), ('no', 'No exprience'), ('three', '3year')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True),
        ),
    ]
