# Generated by Django 2.2.6 on 2019-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0012_auto_20191119_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='highest_qualification',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('DE', 'Deploma')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='years_of_exprience',
            field=models.CharField(choices=[('four', '3year'), ('one', '1year'), ('three', '3year'), ('no', 'No exprience')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='nationality',
            field=models.CharField(choices=[('AN', 'Angola'), ('AL', 'Algeria')], max_length=200, null=True),
        ),
    ]
