# Generated by Django 2.2.6 on 2019-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0013_auto_20191119_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerspersonalifor',
            options={'verbose_name_plural': 'Jobseekers personal info'},
        ),
        migrations.AddField(
            model_name='jobseekerspersonalifor',
            name='middlname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='highest_qualification',
            field=models.CharField(choices=[('PO', 'Postgraduate'), ('BA', 'Bachelor'), ('MA', 'Masters'), ('PH', 'PHD'), ('DE', 'Deploma'), ('CE', 'certificate'), ('NO', 'Non of the above')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='years_of_exprience',
            field=models.CharField(choices=[('', 'No exprience'), ('TEN', '10 year'), ('AB', 'Above ten year'), ('EIGHT', '8 year'), ('NINE', '9 year'), ('one', '1 year'), ('SEVEN', '7 year'), ('FIVE', '5 year'), ('TWO', '2 year'), ('FOUR', '4 year'), ('SIX', ' 6 year')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='location',
            field=models.CharField(choices=[('KG', 'Kigoma'), ('DA', 'Dar es Salaam'), ('KG', 'Kagera'), ('Mw', 'Mwanza'), ('DO', 'Dodoma'), ('', 'Select'), ('AR', 'Arusha')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='nationality',
            field=models.CharField(choices=[('BOT', 'Botswanan'), ('BE', 'Belarusian'), ('AZ', 'Azerbaijani'), ('AL', 'Albanian'), ('BUO', 'Bouvet Island'), ('BAH', 'bahraini'), ('ARU', 'Aruban'), ('BAL', 'Balivian'), ('ANG', 'Angolan'), ('ANT', 'Antarctic'), ('BR', 'Brazilian'), ('AlG', 'Algerian'), ('AUS', 'Australian'), ('', 'Select'), ('BEL', 'Belgian'), ('BAR', 'barbadian'), ('ARG', 'Argentine'), ('BA', 'Bahamian'), ('BO', 'Bosnian OR Herzegovian'), ('ARGE', 'Armenian'), ('BH', 'Bhutene'), ('ANTI', 'Antiguan or Burbudan'), ('BEN', 'Beninese,Beninois'), ('ANGU', 'Anguilban'), ('AUST', 'Austrian'), ('AF', 'Afghan'), ('AN', 'andorran'), ('BELI', 'Belizean'), ('BAN', 'Bangladesh'), ('BER', 'Bermudian')], max_length=200, null=True),
        ),
    ]
