# Generated by Django 2.2.6 on 2019-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0014_auto_20191121_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='highest_qualification',
            field=models.CharField(choices=[('DE', 'Deploma'), ('PO', 'Postgraduate'), ('CE', 'certificate'), ('BA', 'Bachelor'), ('NO', 'Non of the above'), ('PH', 'PHD'), ('MA', 'Masters')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='receive_job_notifation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekersjobinfor',
            name='years_of_exprience',
            field=models.CharField(choices=[('NINE', '9 year'), ('AB', 'Above ten year'), ('TWO', '2 year'), ('FIVE', '5 year'), ('SEVEN', '7 year'), ('', 'No exprience'), ('EIGHT', '8 year'), ('FOUR', '4 year'), ('one', '1 year'), ('SIX', ' 6 year'), ('TEN', '10 year')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='location',
            field=models.CharField(choices=[('DA', 'Dar es Salaam'), ('Mw', 'Mwanza'), ('KG', 'Kigoma'), ('KG', 'Kagera'), ('AR', 'Arusha'), ('', 'Select'), ('DO', 'Dodoma')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspersonalifor',
            name='nationality',
            field=models.CharField(choices=[('BEN', 'Beninese,Beninois'), ('BE', 'Belarusian'), ('AUS', 'Australian'), ('ARG', 'Argentine'), ('AlG', 'Algerian'), ('BER', 'Bermudian'), ('', 'Select'), ('AF', 'Afghan'), ('AUST', 'Austrian'), ('ANTI', 'Antiguan or Burbudan'), ('BR', 'Brazilian'), ('BH', 'Bhutene'), ('BAH', 'bahraini'), ('AN', 'andorran'), ('ARU', 'Aruban'), ('AZ', 'Azerbaijani'), ('ANGU', 'Anguilban'), ('BO', 'Bosnian OR Herzegovian'), ('BELI', 'Belizean'), ('ARGE', 'Armenian'), ('BAL', 'Balivian'), ('BUO', 'Bouvet Island'), ('BEL', 'Belgian'), ('BA', 'Bahamian'), ('AL', 'Albanian'), ('BOT', 'Botswanan'), ('ANG', 'Angolan'), ('BAR', 'barbadian'), ('BAN', 'Bangladesh'), ('ANT', 'Antarctic')], max_length=200, null=True),
        ),
    ]
