# Generated by Django 2.2.6 on 2019-10-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_abooutusmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abooutusmodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Service we provide'},
        ),
    ]
