# Generated by Django 2.2.6 on 2019-10-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20191025_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abooutusmodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'This is about the  Company Profile'},
        ),
    ]
