# Generated by Django 2.2.6 on 2019-10-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_categories_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': ' sub Service '},
        ),
    ]
