# Generated by Django 2.2.6 on 2019-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20191025_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abooutusmodel',
            old_name='file',
            new_name='aboutfile',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='file',
            new_name='carfile',
        ),
    ]
