# Generated by Django 2.2.6 on 2019-10-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_categories_carfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='categoryfile',
            field=models.FileField(blank=True, null=True, upload_to=' serviceCat/'),
        ),
    ]
