# Generated by Django 2.2.6 on 2019-10-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20191026_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='categoryfile',
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, default='/static/img/clients/client-8.png', null=True, upload_to='avatars/'),
        ),
    ]
