# Generated by Django 2.2.6 on 2019-10-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20191026_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abooutusmodel',
            old_name='aboutfile',
            new_name='image',
        ),
    ]
