# Generated by Django 2.2.6 on 2019-10-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20191026_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='abooutusmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Categories'),
        ),
        migrations.AddField(
            model_name='abooutusmodel',
            name='oursolution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
