# Generated by Django 2.2.6 on 2019-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20191026_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abooutusmodel',
            old_name='oursolution',
            new_name='oursolution1',
        ),
        migrations.AddField(
            model_name='abooutusmodel',
            name='oursolution2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='abooutusmodel',
            name='oursolution3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='abooutusmodel',
            name='oursolution4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
