# Generated by Django 2.2.6 on 2019-10-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20191026_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abooutusmodel',
            name='category',
        ),
    ]
