# Generated by Django 2.2.6 on 2019-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_remove_abooutusmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
