# Generated by Django 2.2.6 on 2019-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_auto_20191026_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, default='/static/img/clients/client-8.png', null=True, upload_to='avatars/'),
        ),
    ]
