# Generated by Django 2.2.6 on 2019-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20191026_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
