# Generated by Django 2.2.6 on 2019-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_abooutusmodel_oursolution5'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, default='./img/clients/client-8.png', null=True, upload_to='avatars/')),
            ],
            options={
                'verbose_name_plural': ' Team',
            },
        ),
    ]
