# Generated by Django 2.2.6 on 2019-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_auto_20191028_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='image',
            field=models.FileField(blank=True, default='../static/img/profile-default-lrg.png', null=True, upload_to='avatars/'),
        ),
    ]
