# Generated by Django 2.2.6 on 2019-10-28 15:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiionMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Vision and Mission of the Company',
            },
        ),
    ]
