# Generated by Django 2.2.6 on 2019-10-28 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_visiionmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abooutusmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='massege',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
