# Generated by Django 2.2.6 on 2019-10-29 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_auto_20191028_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatename', models.CharField(blank=True, max_length=250, null=True)),
                ('asociatetitle', models.CharField(blank=True, max_length=250, null=True)),
                ('associatedesc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('associateimage', models.FileField(blank=True, default='../static/img/profile-default-lrg.png', null=True, upload_to='avatars/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': ' Our Associates',
            },
        ),
    ]
