# Generated by Django 2.2.6 on 2019-10-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_associates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associates',
            old_name='asociatetitle',
            new_name='asociateTitle',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='associatedesc',
            new_name='associateDesc',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='associateimage',
            new_name='associateImage',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='associatename',
            new_name='associateName',
        ),
    ]
