# Generated by Django 2.2.6 on 2019-10-30 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_auto_20191029_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, default='../static/img/profile-default-lrg.png', null=True, upload_to='avatars/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_on'], 'verbose_name_plural': ' Customer massege'},
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
