# Generated by Django 2.2.6 on 2019-10-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_auto_20191030_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='image',
            new_name='clentpic',
        ),
    ]
