# Generated by Django 2.2.6 on 2019-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_auto_20191030_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to='pic/'),
        ),
    ]
