# Generated by Django 2.2.6 on 2019-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_contactmodel_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='apply',
            field=models.IntegerField(default=0),
        ),
    ]
