# Generated by Django 2.2.6 on 2019-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_categories_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='apply',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='applied_in',
            field=models.IntegerField(default=0),
        ),
    ]
