# Generated by Django 2.2.6 on 2019-11-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_auto_20191109_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='author',
        ),
    ]
